name: timemanegment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Third Party Packages
  audioplayers: ^6.0.0
  flutter_local_notifications: ^17.0.0
  file_picker: ^8.0.0
  permission_handler: ^11.3.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  share_plus: ^9.0.0
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.2
  flutter_background_service: ^5.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"


# ðŸ‘‡ YE SETTING YAHAN HONI CHAHIYE (Bina Space ke, Left aligned)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

# Flutter Configuration
flutter:
  uses-material-design: true

  # Assets Section
  assets:
    - assets/sounds/